# Example: .github/workflows/node.js.yml

# Name of the workflow
name: Node.js CI

# Specifies when the workflow should be triggered
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Defines the jobs that the workflow will execute
jobs:
  # Job name: build
  build:
    # Specifies the runner environment
    runs-on: ubuntu-latest

    # Defines a matrix strategy to test multiple Node.js versions
    strategy:
      matrix:
        node-version: [16.x, 18.x]

    # Steps to execute
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Build project (if applicable)
        run: npm run build --if-present

      - name: Run tests
        run: npm test
